import Head from "next/head";
import styles from "../styles/Home.module.css";

import Header from "../components/header/header";
import Game from "../components/game/game";
import Footer from "../components/footer/footer";
import { useState, useContext } from "react";
import Rules from "../components/rule/rule";
import Result from "../components/result/result";
import { GameContext } from "../context/game/game.context";

export default function Home() {
  const [toggleRule, setToggleRule] = useState(false);

  const { state } = useContext(GameContext)

  // Rules
  const handleToggleRule = () => {
    setToggleRule(!toggleRule);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Rock-Paper-Scissor-Lizard-Spock</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <Header />
      </header>
      <main>
        {state.toResult ? <Result /> : <Game />}

        {/*  rules */}
        {toggleRule && <Rules handleToggleRule={handleToggleRule} />}
      </main>
      <div>
        <Footer handleToggleRule={handleToggleRule} />
      </div>
    </div>
  );
}
